### Create New Order (only create order for yourself)
POST http://localhost:5173/api/orders
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZDBhZDFiZS1mN2U1LTQ3YzctYjRjMy1jMTcyNTBjYmViYWIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzA2MTg1NTA2fQ.NuJBswV9R4uMd9YhMR6xwY6B_EZpJbXqb055sT3nIHE
Content-Type: application/json

{
    "userId": "ad0ad1be-f7e5-47c7-b4c3-c17250cbebab",
    "addressId": "a1a1a1a1-1234-1234-1234-1234567890ab",
    "fullName": "Admin admin",
    "email": "admin@mail.com",
    "avatar": "https://picsum.photos/1000/1000?random=150",
    "addressLine1": "Street 1 00100",
    "addressLine2": "Helsinki Finland",
    "orderItems": [
        {
            "productId": "bf49c60a-9173-4533-8ca6-182cc7f685eb",
            "variantId": "03fb18b7-6f87-4566-86a5-b50fdfebb817",
            "quantity": 6,
            "price": 32
        }
    ]
}

### Get all orders (Admin only)
GET http://localhost:5173/api/orders
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZDBhZDFiZS1mN2U1LTQ3YzctYjRjMy1jMTcyNTBjYmViYWIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzA2MTg1NTA2fQ.NuJBswV9R4uMd9YhMR6xwY6B_EZpJbXqb055sT3nIHE
Content-Type: application/json

### Update all orders (Admin only)
PATCH http://localhost:5173/api/orders/6ef0c592-49b6-43ea-b404-d0404e1c8163
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZDBhZDFiZS1mN2U1LTQ3YzctYjRjMy1jMTcyNTBjYmViYWIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzA2MTg1NTA2fQ.NuJBswV9R4uMd9YhMR6xwY6B_EZpJbXqb055sT3nIHE
Content-Type: application/json

{
    "status": 1
}