### Create New Product (Only for Admin)
POST https://ecomecho.azurewebsites.net/api/products
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZDBhZDFiZS1mN2U1LTQ3YzctYjRjMy1jMTcyNTBjYmViYWIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzA0NzkzMDc1fQ.JAkjDc-pSUMx_ggrcYfFcNhca1rfClDf2WxGGbD542w
Content-Type: application/json

{
  "title": "Picsum Test Image",
  "description": "A test product with good quality",
  "price": 50,
  "categoryId": "23b984f8-26f7-49a5-82ea-f4f5ddd16eca",
  "variants": [
    {
        "color": 0,
        "size": 1,
        "quantity": 102
    },
    {
        "color": 3,
        "size": 4,
        "quantity": 20
    }
  ],
  "images":[
    {
      "url": "https://picsum.photos/1000/1000?random=1"
    },
    {
      "url": "https://picsum.photos/1000/1000?random=2"
    },
    {
      "url": "https://picsum.photos/1000/1000?random=3"
    }
  ]
}

### Get One Product
GET http://localhost:5173/api/products/46e235cb-57a7-4eaa-b8c0-fc8096daee7b
Content-Type: application/json

### Get All Products
GET http://localhost:5173/api/products
Content-Type:  application/json

### Update one Product
PATCH http://localhost:5173/api/products/46e235cb-57a7-4eaa-b8c0-fc8096daee7b
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkZjM0ZWI1MS1jNTFiLTRjZmEtODQ2ZS05YzRmMDNhOTUwZWMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzAzODYzNDY0fQ.4WfMPF2BfFUKN2ZczSonP2eVvpqLrNmbNxQrD0rAX7A
Content-Type: application/json

{
  "price": 69.99
}

### Delete one product 
DELETE http://localhost:5173/api/products/eebd0309-0bec-43d7-8452-394508488e9d
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkZjM0ZWI1MS1jNTFiLTRjZmEtODQ2ZS05YzRmMDNhOTUwZWMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzAzODYzNDY0fQ.4WfMPF2BfFUKN2ZczSonP2eVvpqLrNmbNxQrD0rAX7A
Content-Type:  application/json
