### Create New User (For all)
POST http://localhost:5173/api/users
Content-Type: application/json

{
  "firstName": "New",
  "lastName": "Man",
  "email": "newman2@mail.com",
  "password": "Password123",
  "avatar":"https://images.unsplash.com/photo-1560807707-8cc77767d783?q=80&w=2535&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}

# {
#   "firstName": "Admin",
#   "lastName": "Admin",
#   "email": "admin@mail.com",
#   "password": "admin"
# }

### Create New User (For Admin)
POST http://localhost:5173/api/users/admin/create-user
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4OTFiNGU3OS0zZmNiLTRkMGItOTM2My02YmM3N2MwOTVmNzEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzA0NDQ1MTIzfQ.18b6aDcUSuXYpONF3uRlERk3XlcEMe90XgRos8SewNg
Content-Type: application/json

{
  "firstName": "New",
  "lastName": "Man",
  "email": "newman2@mail.com",
  "password": "Password123",
  "role": 1,
  "avatar":"https://images.unsplash.com/photo-1560807707-8cc77767d783?q=80&w=2535&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}

### User Login as Admin
POST https://ecomecho.azurewebsites.net/api/users/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "admin"
}

### User Login as Customer
POST http://localhost:5173/api/users/login
Content-Type: application/json

{
  "email": "cena@mail.com",
  "password": "password"
}

### Check Email Availability
POST http://localhost:5173/api/users/is-available
Content-Type: application/json

{
  "email": "jane.doe@example.com"
}

### Get All Users
GET http://localhost:5173/api/users
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4OTFiNGU3OS0zZmNiLTRkMGItOTM2My02YmM3N2MwOTVmNzEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzA0NDQ1MTIzfQ.18b6aDcUSuXYpONF3uRlERk3XlcEMe90XgRos8SewNg
Content-Type: application/json

### Get One User
GET http://localhost:5173/api/users/611a0192-8b2e-4997-a8c8-59b93674d33b
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4OTFiNGU3OS0zZmNiLTRkMGItOTM2My02YmM3N2MwOTVmNzEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzA0NDQ1MTIzfQ.18b6aDcUSuXYpONF3uRlERk3XlcEMe90XgRos8SewNg
Content-Type: application/json

### Get Current User Profile
GET http://localhost:5173/api/users/profile
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3NjA0NTRmYS00YWYxLTRhZTYtOWIxOC1lZDNhZWM0YmUyYTkiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJjZW5hQG1haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ3VzdG9tZXIiLCJleHAiOjE3MDQ1Mjc0MzN9.d4k7pWe08SLGWAdBKgla1VjtV2yPqGOxz-PgKOcVr_k
Content-Type: application/json

### Update Any User as Admin
PATCH http://localhost:5173/api/users/891b4e79-3fcb-4d0b-9363-6bc77c095f71
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4OTFiNGU3OS0zZmNiLTRkMGItOTM2My02YmM3N2MwOTVmNzEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzA0NDQ1MTIzfQ.18b6aDcUSuXYpONF3uRlERk3XlcEMe90XgRos8SewNg
Content-Type: application/json

{
  "firstName": "Admin only"
}

### Update current user info (User can only update his own info)
PATCH http://localhost:5173/api/users/profile
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4OTFiNGU3OS0zZmNiLTRkMGItOTM2My02YmM3N2MwOTVmNzEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzA0NDQ5ODg1fQ.3mhLDVM5Hc1ObnobmSGfpX6Mh_DwmJGXoPAP6QQPgZI
Content-Type: application/json

{
  "firstName": "Jane Wonderful Admin 1"
}

### Delete User
DELETE http://localhost:5173/api/users/c3e55cc3-6a7a-4c6c-9342-0a6f2a226be2
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZDBhZDFiZS1mN2U1LTQ3YzctYjRjMy1jMTcyNTBjYmViYWIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzA0NjEwNjAzfQ.argDyed_N0e1IgW3Ig8hx5SsMShXP70VoV8iknd8ILU
Content-Type: application/json


### Change password
POST http://localhost:5173/api/users/change-password
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3NjA0NTRmYS00YWYxLTRhZTYtOWIxOC1lZDNhZWM0YmUyYTkiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJjZW5hQG1haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ3VzdG9tZXIiLCJleHAiOjE3MDQ1MjEzNjl9.Ul6EM6gcJ8Q87yKAnG_vSAnF4lxBDuiq6q2d7J2uM28
Content-Type: application/json

{
  "currentPassword": "password",
  "newPassword": "password1",
  "confirmNewPassword": "password1"
}