### Create New User
POST http://localhost:5173/api/users
Content-Type: application/json

# {
#   "firstName": "John",
#   "lastName": "Doe",
#   "email": "john.doe@example.com",
#   "password": "Password123"
# }
{
  "firstName": "Admin",
  "lastName": "Admin",
  "email": "admin@mail.com",
  "password": "admin"
}

### User Login as Admin
POST http://localhost:5173/api/users/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "admin"
}

### User Login as Customer John
POST http://localhost:5173/api/users/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "Password123"
}

### Check Email Availability
POST http://localhost:5173/api/users/is-available
Content-Type: application/json

{
  "email": "jane.doe@example.com"
}

### Get All Users
GET http://localhost:5173/api/users
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmZTc4MTMwYy00MWZlLTRhY2YtODdmMy1kMjhiZmNjMjNhNGMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzAzNDMwMjE1fQ.Uv7qP7iSR7uONXckOsfBTQI7chXlyELTzrIR0Saapvg
Content-Type: application/json

### Get One User
GET http://localhost:5173/api/users/688f3ab6-fbc3-4e41-a7b2-870eeea446ea
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmZTc4MTMwYy00MWZlLTRhY2YtODdmMy1kMjhiZmNjMjNhNGMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzAzNDMwMjE1fQ.Uv7qP7iSR7uONXckOsfBTQI7chXlyELTzrIR0Saapvg
Content-Type: application/json

### Get Current User Profile
GET http://localhost:5173/api/users/profile
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlNjhhZGQyMi02ZDFlLTRkODQtYjkwMS1kNDZlMWU1ZmEwYzYiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzA0MDIyNzEyfQ.HkumCpNONDnEQ_R_Z5ykajZcMrFhZnQ5HtzlG8bnVwQ
Content-Type: application/json

### Update Any User as Admin
PATCH http://localhost:5173/api/users/e68add22-6d1e-4d84-b901-d46e1e5fa0c6
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmZTc4MTMwYy00MWZlLTRhY2YtODdmMy1kMjhiZmNjMjNhNGMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzAzNDMwMjE1fQ.Uv7qP7iSR7uONXckOsfBTQI7chXlyELTzrIR0Saapvg
Content-Type: application/json

{
  "email": "Admin 4"
}

### Update current user info (User can only update his own info)
PATCH http://localhost:5173/api/users/profile
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODhmM2FiNi1mYmMzLTRlNDEtYTdiMi04NzBlZWVhNDQ2ZWEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJqYW5lLmRvZUBleGFtcGxlLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkN1c3RvbWVyIiwiZXhwIjoxNzAzNDMyMDgzfQ.T1Ys_Vvebjhnf3EZIWND7IhdjaXV5djJhoF9Z4RxZts
Content-Type: application/json

{
  "firstName": "Jane Wonderful",
  "lastName": "Doe Updated"
}

### Delete User
DELETE http://localhost:5173/api/users/943f8ad0-7d12-45fb-a2f8-effe919c47a6
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmZTc4MTMwYy00MWZlLTRhY2YtODdmMy1kMjhiZmNjMjNhNGMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzAzNDMwMjE1fQ.Uv7qP7iSR7uONXckOsfBTQI7chXlyELTzrIR0Saapvg
Content-Type: application/json
